function [] = constructJSmolPage_alignment(JSmolPagePath, width, height, structure_1, structure_2, webGLOp)
%CONSTRUCTJSMOLPAGE Summary of this function goes here
%   Detailed explanation goes here

if webGLOp
    useStr = 'WEBGL HTML5';
else
    useStr = 'HTML5';
end



if isdeployed
    js2path = fullfile(ctfroot,'lib','jsmol','js2');
    filename = fullfile(tempdir, 'JSmol_matlab.htm');
else
    js2path = fullfile(JSmolPagePath,'js2');
    filename = fullfile(JSmolPagePath, 'JSmol_matlab.htm');
    jsmolMinPath = fullfile(JSmolPagePath,'JSmol.min.js');
    jsmolMinGLPath = fullfile(JSmolPagePath,'JSmol.GLmol.min.js');
end


fid = fopen(filename, 'w');

scriptStr = sprintf(['set antialiasDisplay; load %s; load append %s;', ...
            'background {0.94, 0.94, 0.94}; select 1.1, 2.1; cartoon ON; cpk off; wireframe off; frame all; select 1.1;', ...
            'color [%d %d %d]; select 2.1; color [%d %d %d]'], ...
            structure_1.path, structure_2.path, ...
            structure_1.color(1), structure_1.color(2), structure_1.color(3), ...
            structure_2.color(1), structure_2.color(2), structure_2.color(3));
        
htmlCode = [...
        '<!DOCTYPE html>', ...
            '\n<html>', ...
            '\n<head>', ...
            '\n<meta charset="utf-8">', ...
            '\n<title>JSmol HTML5</title>', ...
            '\n<script type="text/javascript" src="%s"></script>', ...
            '\n<script type="text/javascript" src="%s"></script>', ...
            '\n<script type="text/javascript">', ...
            '\nvar jmolApplet0; // set up in HTML table, below', ...
            '\nvar s = document.location.search;', ...
            '\nJmol._debugCode = (s.indexOf("debugcode") >= 0);', ...
            '\nvar Info = {', ...
            '\nwidth: %d,', ...
            '\nheight: %d,', ...
            '\ndebug: false,', ...
            '\ncolor: "0xFFFFFF",', ...
            '\naddSelectionOptions: false,', ...
            '\nuse: "%s",', ...
            '\nj2sPath: "%s",', ...
            '\nscript: "%s",', ...
            '\ndisableJ2SLoadMonitor: false,', ...
            '\ndisableInitialConsole: false,', ...
            '\nallowJavaScript: false', ...
            '\n}', ...
            '\n\n', ...
            '\n$(document).ready(function() {', ...
            '\n$("#appdiv").html(Jmol.getAppletHtml("jmolApplet0", Info));', ...
            '\n})', ...
            '\n', ...
            '\nvar lastPrompt=0;', ...
            '\n</script>', ...
            '\n</head>', ...
            '\n<body>', ...
            '\n<div id="appdiv" style="width:%dpx"></div>', ...
            '\n</body>', ...
            '\n</html>', ...
            '\n' ...
            ];
        
fprintf(fid, htmlCode, jsmolMinPath, jsmolMinGLPath, width, height, useStr, js2path, scriptStr, width);

fclose(fid);

end

